### ISSUE TITLE
npm throws errors upon test failure

### ISSUE THREAD

**Issue by mycargus** [mycargus/nightwatch-docker-grid#12]
When a test fails, npm throws an error. The error doesn't appear to affect test results or any other functionality, but it's verbose and potentially confusing to an end user.

**Comment by rmNyro** [comment]
Found https://github.com/npm/npm/issues/6124#issuecomment-317198898 and I think it is the way to go since it is a nightwatch/npm related "issue".

**Comment by mycargus** [comment]
awesome, thank you so much!
