### ISSUE TITLE
Rename repo 

### ISSUE THREAD

**Issue by mycargus** [mycargus/nightwatch-docker-grid#4]
['coz Docker says so](https://www.andreas-jung.com/contents/dont-use-docker-in-github-repo-names-or-as-twitter-handle)

While I seriously doubt Docker would ever come after this little repo, I do want to comply with their licensing.

**Comment by SgtPooki** [comment]
Do it!

**Comment by rmNyro** [comment]
Do it! :)

**Comment by mycargus** [comment]
Docker specifically says not to use "docker" as the first word in a repo. Issue resolved.
