### ISSUE TITLE
Presence in dockerhub?

### ISSUE THREAD

**Issue by psociety** [mycargus/nightwatch-docker-grid#40]
Ty for creating this image!
Couldn't it be available on dockerhub?

I expected to run it like: 
`docker-compose run --rm -v $PWD:/app --workdir /app/ui-tests nightwatch `

(`ui-tests` folder has `nightwatch.json`,`tests` folder,`commands` folder, etc..)

**Comment by mycargus** [comment]
Hullo! 

Sure, we can publish the image to dockerhub. 

Are you wanting to use the image outside of the structure defined in this project? I ask because you'll need to tweak the nightwatch.json config if that's the case. Just want to be clear about expectations. :)

**Comment by psociety** [comment]
As i see the project uses an image of the app to test it, but if i set a workdir like in the command that i posted, won't it work too without needing?

**Comment by mycargus** [comment]
I'm not sure I understand what you're saying. Can you explain to me what you want to accomplish?

**Comment by psociety** [comment]
soz for my bad comm skils :(
Having the following project structure:
- core/
- public/
- doc/
- vendor/
- ui-tests/

I expect to simply run a command and get the nightwatch tests at ui-tests folder executed.

**Comment by mycargus** [comment]
No worries! I just want to make sure I understand what you need so that I can help. 😃  

Yes, we can publish a nightwatch docker image to dockerhub that will let you mount a directory such as ui-tests. Feel free to submit a PR that references this issue, or I'll try to get to it in the next couple of weeks.

**Comment by mycargus** [comment]
@psociety I meant to ask you this and I forgot --- Does our published nightwatch image meet your needs? Anything we can do to improve it?

**Comment by psociety** [comment]
So far i didn't have any problem. Now i can run my tests con CLI easily :)

**Comment by mycargus** [comment]
Excellent!
