### ISSUE TITLE
Deeper contribution possible?

### ISSUE THREAD

**Issue by rmNyro** [mycargus/nightwatch-docker-grid#8]
Hey!

I don't know if you've read https://github.com/mycargus/nightwatch-docker-grid/pull/6#issuecomment-324909538 but I'd like to build a testing grid such as this one around a project I have and have made lots of improvements/fixes of the work you've done by trying to adapt it to my project.

So my "question" is, is there a way I can do a big contribution? I'm afraid this potential contribution will never be make it if delayed too much. Maybe a big PR made of small intelligible commits? Atomic commits as suggested in my comment? Tell me, I'd like to participate/help. :)

cheers

EDIT: I've bundled my commits, I'll make a PR, you can close this if it suits you

**Comment by mycargus** [comment]
Wow, thanks for all the work! Usually I'm a fan of small-as-possible PRs with limited scope, but I'll take a look this week.

Sorry I've not been more available to review your requests. I've had to focus on my employer's needs lately. Normally I'm not so busy. :)

I'll close this thread and we can continue discussions in the other issue you opened.
